name: Feature request
description: Suggest an idea for this project
title: '<title>'
labels: [enhancement]
body:
- type: textarea
  id: testid
  attributes:
    label: Describe the solution/feature you'd like.
    # description: |
  validations:
    required: true
