name: Bug Report
description: File a bug/issue
title: "<title>"
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the bug you encountered: https://github.com/canonical/steam-snap/issues?q=label%3Abug.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Have you checked the wiki for solutions?
    description: |
      Please check the wiki to see if your issue is addressed: https://github.com/canonical/steam-snap/wiki. If you do any troubleshooting from the wiki, please include it in the final section of this report.
    options:
    - label: I have searched the wiki
      required: true
- type: checkboxes
  attributes:
    label: Is this a Steam Snap-specific issue?
    description: |
      Please make sure your issue is exclusive to the Steam Snap and doesn't occur in the Steam deb. If this is a deb issue, then open an issue in Valve's repository instead: https://github.com/ValveSoftware/steam-for-linux. If you don't know, leave this unchecked.
    options:
    - label: This is a Steam Snap-specific issue
      required: false
- type: textarea
  id: behavior
  attributes:
    label: Current Behavior
    description: |
      A concise description of what you're experiencing.
    placeholder: |
      A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      A concise description of what you expected to happen.
    placeholder: |
      A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: |
      Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error/undesired behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Output of `snap run steam.report --no-submit`. More info on this command [here](https://github.com/canonical/steam-snap/wiki/Troubleshooting#submitting-a-steam-report).
    placeholder: |
      os_release: 
          name:               
          version:            
      snap_info: 
          steam_revision:     
          snapd_revision:     
      lspci: 
          00:00.0:                       
      glxinfo: 
          gpu:                
          gpu_version:        
      lscpu: 
          model_name:         
      xdg_current_desktop:    
      desktop_session:        
    render: yaml
  validations:
    required: true
- type: dropdown
  attributes:
    label: gaming-graphics-core22 version
    description: |
      Please select the version(s) of the [gaming-graphics-core22](https://github.com/canonical/gaming-graphics/) Snap you have tried/this issue affects. More info on this [here](https://github.com/canonical/steam-snap/wiki/FAQ#how-do-i-use-a-different-mesagraphics-version).

      If the issue is graphics/GPU related, it is very useful to us if you try each gaming-graphics-core22 branch and report observed behavior differences.
    options:
      - kisak-fresh (default)
      - kisak-turtle
      - oibaf-latest
    multiple: true
  validations:
    required: false
- type: textarea
  attributes:
    label: |
      Anything else?
    description: |
      Screenshots? [Logs](https://github.com/canonical/steam-snap/wiki/Troubleshooting#view-logs)? Links? Anything that will give us more context about the issue. If pasting logs, please format them by surrounding the text with ```.

      Please include [Steam logs](https://github.com/canonical/steam-snap/wiki/Troubleshooting#view-logs) (if applicable) and any additional steps you took to troubleshoot. For troubleshooting ideas, see the [wiki](https://github.com/canonical/steam-snap/wiki).

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
