name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. https://github.com/canonical/steam-snap/issues?q=
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Have you checked the Wiki for solutions?
    description: Please check the Wiki to see if your issue is addressed. https://github.com/canonical/steam-snap/wiki
    options:
    - label: I have searched the Wiki
      required: true
- type: checkboxes
  attributes:
    label: Does your issue occur in the Steam deb?
    description: "Please make sure your issue *only* occurs in the Snap. Otherwise, open an issue in Valve's repository: https://github.com/ValveSoftware/steam-for-linux"
    options:
    - label: This is a Steam Snap-specific issue
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: "A concise description of what you're experiencing."
    placeholder: "A concise description of what you're experiencing."
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error/undesired behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: "Output of `snap run steam.report --no-submit`. More info on this command [here](https://github.com/canonical/steam-snap/wiki/Troubleshooting#submitting-a-steam-report
)."
    placeholder: |
      os_release: 
          name:               
          version:            
      snap_info: 
          steam_revision:     
          snapd_revision:     
      lspci: 
          00:00.0:                       
      glxinfo: 
          gpu:                
          gpu_version:        
      lscpu: 
          model_name:         
      xdg_current_desktop:    
      desktop_session:        
    render: yaml
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Screenshots? Logs? Links? Anything that will give us more context about the issue. If pasting logs, please format them by surrounding the text with ``` ```.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
