name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. https://github.com/canonical/steam-snap/issues?q=
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Have you checked the Wiki for solutions?
    description: Please check the Wiki to see if your issue is addressed. https://github.com/canonical/steam-snap/wiki
    options:
    - label: I have searched the Wiki
      required: true
- type: checkboxes
  attributes:
    label: Does your issue occur in the Steam deb?
    description: Please make sure your issue *only* occurs in the Snap, otherwise, open an issue in Valve's repository: https://github.com/ValveSoftware/steam-for-linux
    options:
    - label: This is a Steam Snap-specific issue
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
